# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExtractionAutomationTool.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setStyleSheet("* {\n"
"\n"
"background-color: white;\n"
"}\n"
"QTabBar::tab{\n"
"background-color:white;\n"
"height: 40px;\n"
"min-width: 50px;\n"
"width:150px;\n"
"color: #156abf;\n"
"\n"
"}\n"
"QTabBar::tab:selected {\n"
"background-color:#48a5e8;\n"
"border-top-right-radius: 4px;\n"
"border-top-left-radius: 4px;\n"
"color:white;\n"
"}\n"
"#infosGB,#delimiterGB{\n"
"border: 1px solid red;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255,255,255,0);\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 5px;\n"
" } \n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 0, 781, 701))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabs.setFont(font)
        self.tabs.setStyleSheet("border: Opx;")
        self.tabs.setTabsClosable(False)
        self.tabs.setObjectName("tabs")
        self.indexesTab = QtWidgets.QWidget()
        self.indexesTab.setMinimumSize(QtCore.QSize(100, 465))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.indexesTab.setFont(font)
        self.indexesTab.setStyleSheet("height : 50px;\n"
"")
        self.indexesTab.setObjectName("indexesTab")
        self.label = QtWidgets.QLabel(self.indexesTab)
        self.label.setGeometry(QtCore.QRect(150, 20, 411, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#107ac7;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.startButton = QtWidgets.QPushButton(self.indexesTab)
        self.startButton.setGeometry(QtCore.QRect(600, 570, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color:#107ac7;\n"
"color: white;\n"
"\n"
"")
        self.startButton.setObjectName("startButton")
        self.label_2 = QtWidgets.QLabel(self.indexesTab)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/infos_icon.png"))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.indexesTab)
        self.textEdit.setGeometry(QtCore.QRect(130, 110, 541, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.delimiterGB = QtWidgets.QGroupBox(self.indexesTab)
        self.delimiterGB.setGeometry(QtCore.QRect(70, 300, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delimiterGB.setFont(font)
        self.delimiterGB.setStyleSheet("color:#107ac7;")
        self.delimiterGB.setObjectName("delimiterGB")
        self.delimiterCB = QtWidgets.QComboBox(self.delimiterGB)
        self.delimiterCB.setGeometry(QtCore.QRect(240, 30, 101, 22))
        self.delimiterCB.setObjectName("delimiterCB")
        self.delimiterCB.addItem("")
        self.delimiterCB.addItem("")
        self.delimiterCB.addItem("")
        self.label_3 = QtWidgets.QLabel(self.delimiterGB)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.infosGB = QtWidgets.QGroupBox(self.indexesTab)
        self.infosGB.setGeometry(QtCore.QRect(430, 230, 331, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infosGB.setFont(font)
        self.infosGB.setStyleSheet("color:#107ac7;")
        self.infosGB.setObjectName("infosGB")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.infosGB)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 20, 261, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.NETagsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.NETagsLabel.setText("")
        self.NETagsLabel.setObjectName("NETagsLabel")
        self.horizontalLayout.addWidget(self.NETagsLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.OtherTagsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.OtherTagsLabel.setText("")
        self.OtherTagsLabel.setObjectName("OtherTagsLabel")
        self.horizontalLayout_3.addWidget(self.OtherTagsLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.UnkTagsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.UnkTagsLabel.setText("")
        self.UnkTagsLabel.setObjectName("UnkTagsLabel")
        self.horizontalLayout_4.addWidget(self.UnkTagsLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.lineEdit = QtWidgets.QLineEdit(self.indexesTab)
        self.lineEdit.setGeometry(QtCore.QRect(70, 240, 181, 41))
        self.lineEdit.setStyleSheet("border-bottom: 2px solid red;")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.uploadFileButton = QtWidgets.QPushButton(self.indexesTab)
        self.uploadFileButton.setGeometry(QtCore.QRect(290, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uploadFileButton.setFont(font)
        self.uploadFileButton.setStyleSheet("border-right: 2px solid #107ac7;\n"
"border-bottom: 2px solid #107ac7;\n"
"color:#107ac7;\n"
"\n"
"")
        self.uploadFileButton.setObjectName("uploadFileButton")
        self.errorContainer = QtWidgets.QGroupBox(self.indexesTab)
        self.errorContainer.setGeometry(QtCore.QRect(470, 460, 301, 81))
        self.errorContainer.setStyleSheet("background-color:rgba(252, 90, 78,1);\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;")
        self.errorContainer.setTitle("")
        self.errorContainer.setObjectName("errorContainer")
        self.label_4 = QtWidgets.QLabel(self.errorContainer)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 31, 31))
        self.label_4.setStyleSheet("background-color:transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("assets/error_icon.png"))
        self.label_4.setObjectName("label_4")
        self.errorLabel = QtWidgets.QLabel(self.errorContainer)
        self.errorLabel.setGeometry(QtCore.QRect(70, 20, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color:white;")
        self.errorLabel.setText("")
        self.errorLabel.setWordWrap(True)
        self.errorLabel.setObjectName("errorLabel")
        self.successContainer = QtWidgets.QGroupBox(self.indexesTab)
        self.successContainer.setGeometry(QtCore.QRect(80, 559, 361, 71))
        self.successContainer.setStyleSheet("background-color:#41fa50;\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"")
        self.successContainer.setTitle("")
        self.successContainer.setObjectName("successContainer")
        self.label_6 = QtWidgets.QLabel(self.successContainer)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.successContainer)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("assets/ok_icon.png"))
        self.label_8.setObjectName("label_8")
        self.confirmButton = QtWidgets.QPushButton(self.indexesTab)
        self.confirmButton.setGeometry(QtCore.QRect(590, 400, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.confirmButton.setFont(font)
        self.confirmButton.setStyleSheet("background-color:#41fa50;\n"
"color: white;\n"
"\n"
"")
        self.confirmButton.setObjectName("confirmButton")
        self.scrollArea = QtWidgets.QScrollArea(self.indexesTab)
        self.scrollArea.setGeometry(QtCore.QRect(20, 380, 431, 161))
        self.scrollArea.setStyleSheet("*{\n"
"background-color:white;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 431, 161))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newWordsSA = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.newWordsSA.setWidgetResizable(True)
        self.newWordsSA.setObjectName("newWordsSA")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 203, 141))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:#107ac7;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.newWordsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.newWordsLabel.setStyleSheet("background-color:white;")
        self.newWordsLabel.setText("")
        self.newWordsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.newWordsLabel.setObjectName("newWordsLabel")
        self.verticalLayout.addWidget(self.newWordsLabel)
        self.newWordsSA.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.addWidget(self.newWordsSA)
        self.newTagsSA = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.newTagsSA.setWidgetResizable(True)
        self.newTagsSA.setObjectName("newTagsSA")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 202, 141))
        self.scrollAreaWidgetContents.setStyleSheet("background-color:white;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.newTagscontainer = QtWidgets.QHBoxLayout()
        self.newTagscontainer.setObjectName("newTagscontainer")
        self.horizontalLayout_6.addLayout(self.newTagscontainer)
        self.newTagsSA.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.newTagsSA)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.tabs.addTab(self.indexesTab, "")
        self.rechercheTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rechercheTab.setFont(font)
        self.rechercheTab.setStyleSheet("*{\n"
"background-color:white;\n"
"}\n"
"")
        self.rechercheTab.setObjectName("rechercheTab")
        self.groupBox = QtWidgets.QGroupBox(self.rechercheTab)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 731, 311))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:#107ac7;")
        self.groupBox.setObjectName("groupBox")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(40, 40, 601, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgba(252, 90, 78,1);")
        self.label_10.setObjectName("label_10")
        self.rename_selectedGB = QtWidgets.QGroupBox(self.groupBox)
        self.rename_selectedGB.setGeometry(QtCore.QRect(20, 110, 311, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rename_selectedGB.setFont(font)
        self.rename_selectedGB.setStyleSheet("color:#1366eb;")
        self.rename_selectedGB.setObjectName("rename_selectedGB")
        self.tags_to_addCombobox = QtWidgets.QComboBox(self.rename_selectedGB)
        self.tags_to_addCombobox.setGeometry(QtCore.QRect(160, 0, 161, 31))
        self.tags_to_addCombobox.setObjectName("tags_to_addCombobox")
        self.confirm_new_nameButton = QtWidgets.QPushButton(self.rename_selectedGB)
        self.confirm_new_nameButton.setGeometry(QtCore.QRect(184, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_new_nameButton.setFont(font)
        self.confirm_new_nameButton.setStyleSheet("background-color:#41fa50;\n"
"color: white;\n"
"")
        self.confirm_new_nameButton.setObjectName("confirm_new_nameButton")
        self.label_11 = QtWidgets.QLabel(self.rename_selectedGB)
        self.label_11.setGeometry(QtCore.QRect(20, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.rename_selectedGB)
        self.label_12.setGeometry(QtCore.QRect(30, 80, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.undo_selectedButton = QtWidgets.QPushButton(self.rename_selectedGB)
        self.undo_selectedButton.setGeometry(QtCore.QRect(20, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.undo_selectedButton.setFont(font)
        self.undo_selectedButton.setStyleSheet("background-color:rgba(252, 90, 78,1);\n"
"color:white;")
        self.undo_selectedButton.setObjectName("undo_selectedButton")
        self.rename_tag_edit = QtWidgets.QLineEdit(self.rename_selectedGB)
        self.rename_tag_edit.setGeometry(QtCore.QRect(150, 39, 131, 31))
        self.rename_tag_edit.setStyleSheet("border-bottom: 2px solid red;")
        self.rename_tag_edit.setObjectName("rename_tag_edit")
        self.update_success_label = QtWidgets.QLabel(self.rename_selectedGB)
        self.update_success_label.setGeometry(QtCore.QRect(80, 160, 151, 16))
        self.update_success_label.setStyleSheet("color:#41fa50;")
        self.update_success_label.setObjectName("update_success_label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(379, 109, 351, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 51, 41))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("assets/warning_icon.png"))
        self.label_13.setObjectName("label_13")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setGeometry(QtCore.QRect(73, 30, 261, 81))
        self.textEdit_2.setObjectName("textEdit_2")
        self.searcch_word_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.searcch_word_edit.setGeometry(QtCore.QRect(20, 140, 171, 31))
        self.searcch_word_edit.setStyleSheet("border-bottom: 2px solid #107ac7;")
        self.searcch_word_edit.setObjectName("searcch_word_edit")
        self.search_wordButton = QtWidgets.QPushButton(self.groupBox_2)
        self.search_wordButton.setGeometry(QtCore.QRect(220, 130, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.search_wordButton.setFont(font)
        self.search_wordButton.setStyleSheet("background-color:#107ac7;\n"
"color: white;\n"
"\n"
"")
        self.search_wordButton.setObjectName("search_wordButton")
        self.edit_lines_SA = QtWidgets.QScrollArea(self.rechercheTab)
        self.edit_lines_SA.setGeometry(QtCore.QRect(20, 360, 741, 211))
        self.edit_lines_SA.setWidgetResizable(True)
        self.edit_lines_SA.setObjectName("edit_lines_SA")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 741, 211))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 691, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.editvbox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.editvbox.setContentsMargins(0, 0, 0, 0)
        self.editvbox.setObjectName("editvbox")
        self.edit_lines_SA.setWidget(self.scrollAreaWidgetContents_4)
        self.confirm_allButton = QtWidgets.QPushButton(self.rechercheTab)
        self.confirm_allButton.setGeometry(QtCore.QRect(570, 600, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_allButton.setFont(font)
        self.confirm_allButton.setStyleSheet("background-color:#04bd35;\n"
"color: white;\n"
"")
        self.confirm_allButton.setObjectName("confirm_allButton")
        self.tabs.addTab(self.rechercheTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Corpus Sources Automation Tool"))
        self.label.setText(_translate("MainWindow", "Building HMM Data Sources"))
        self.startButton.setText(_translate("MainWindow", "Start Extraction"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600; color:#3486b3;\">Please respect input file format</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600; color:#3486b3;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\"> - </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Input file must be encoded with </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#ff0000;\">Windows-1256 arabic encoding</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">.</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#3486b3;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\">  - </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Input file must be formatted as follow: word [Tab] Tag.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">  - Please choose a concistent file that contains meaningfull sentences for better model results.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">  - Make sure that the file is well sentences delimited using one of available delimiters.</span></p></body></html>"))
        self.delimiterGB.setTitle(_translate("MainWindow", "Delimter :"))
        self.delimiterCB.setItemText(0, _translate("MainWindow", "---"))
        self.delimiterCB.setItemText(1, _translate("MainWindow", "***"))
        self.delimiterCB.setItemText(2, _translate("MainWindow", "</EOS>"))
        self.label_3.setText(_translate("MainWindow", "Choose sentences delimiter used in the file :"))
        self.infosGB.setTitle(_translate("MainWindow", "Infos :"))
        self.label_5.setText(_translate("MainWindow", "Total NE Tags:"))
        self.label_7.setText(_translate("MainWindow", "Total Lines :"))
        self.label_9.setText(_translate("MainWindow", "Unrecognized :"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Please choose a source file..."))
        self.uploadFileButton.setText(_translate("MainWindow", "Upload File"))
        self.label_6.setText(_translate("MainWindow", "Information extracted successfully !"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm New NE Tags"))
        self.label_14.setText(_translate("MainWindow", "New detected Lines"))
        self.tabs.setTabText(self.tabs.indexOf(self.indexesTab), _translate("MainWindow", "Information Extractor"))
        self.groupBox.setTitle(_translate("MainWindow", "Edit Tags :"))
        self.label_10.setText(_translate("MainWindow", "Before submitting new corpus, please make sure to check validation of the sources you are adding"))
        self.rename_selectedGB.setTitle(_translate("MainWindow", "Tags to be added :"))
        self.confirm_new_nameButton.setText(_translate("MainWindow", "Confirm"))
        self.label_11.setText(_translate("MainWindow", "Change it to :"))
        self.label_12.setText(_translate("MainWindow", "or"))
        self.undo_selectedButton.setText(_translate("MainWindow", "Delete"))
        self.rename_tag_edit.setPlaceholderText(_translate("MainWindow", "Enter the new tag name.."))
        self.update_success_label.setText(_translate("MainWindow", "Tag name updated successfully !"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Edit wrong tags:"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffaa00;\">Warning </span>:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Be aware of altering such Data !</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Please make sure that you understand the critical change you are about to make. </span></p></body></html>"))
        self.searcch_word_edit.setPlaceholderText(_translate("MainWindow", "Search for a word ..."))
        self.search_wordButton.setText(_translate("MainWindow", "Search"))
        self.confirm_allButton.setText(_translate("MainWindow", "Confirm all changes"))
        self.tabs.setTabText(self.tabs.indexOf(self.rechercheTab), _translate("MainWindow", "Sources Edition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
