import re
NE_TAG_lABELS=['PERSON',
                        'ORG',
                        'OTHER',
                        'LOC',
                        'DATE',
                        'OCLUE',
                        'DCLUE',
                        'LCLUE',
                        'PCLUE',
                        'PREP',
                        'PUNC',
                        'CONJ',
                        'NPREFIX',
                        'DEF']